create table spatial_ref_sys
(
    srid      integer not null
        primary key
        constraint spatial_ref_sys_srid_check
            check ((srid > 0) AND (srid <= 998999)),
    auth_name varchar(256),
    auth_srid integer,
    srtext    varchar(2048),
    proj4text varchar(2048)
);

alter table spatial_ref_sys
    owner to myuser;

grant select on spatial_ref_sys to public;

create table bus_arrival_raw
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6),
    deleted_at        timestamp(6),
    updated_at        timestamp(6),
    arrival_msg1      varchar(255),
    arrival_msg2      varchar(255),
    ars_id            varchar(255),
    avg_coefficient1  double precision,
    avg_coefficient2  double precision,
    bus_type1         integer,
    bus_type2         integer,
    collected_at      timestamp(6) not null,
    congestion_div1   integer,
    congestion_div2   integer,
    congestion_num1   integer,
    congestion_num2   integer,
    data_timestamp    varchar(255),
    detour_yn         varchar(255),
    direction         varchar(255),
    exp_coefficient1  double precision,
    exp_coefficient2  double precision,
    goal_time1        integer,
    goal_time2        integer,
    is_arrive1        varchar(255),
    is_arrive2        varchar(255),
    is_full1          varchar(255),
    is_full2          varchar(255),
    is_last1          varchar(255),
    is_last2          varchar(255),
    kal_coefficient1  double precision,
    kal_coefficient2  double precision,
    kal_predict_time1 integer,
    kal_predict_time2 integer,
    main2stop_id1     varchar(255),
    main2stop_id2     varchar(255),
    main2stop_ord1    integer,
    main2stop_ord2    integer,
    main2stop_sec1    integer,
    main2stop_sec2    integer,
    main3stop_id1     varchar(255),
    main3stop_id2     varchar(255),
    main3stop_ord1    integer,
    main3stop_ord2    integer,
    main3stop_sec1    integer,
    main3stop_sec2    integer,
    main_stop_id1     varchar(255),
    main_stop_id2     varchar(255),
    main_stop_ord1    integer,
    main_stop_ord2    integer,
    main_stop_sec1    integer,
    main_stop_sec2    integer,
    neu_coefficient1  double precision,
    neu_coefficient2  double precision,
    neu_predict_time1 integer,
    neu_predict_time2 integer,
    next_bus_yn       varchar(255),
    next_stop_id1     varchar(255),
    next_stop_id2     varchar(255),
    next_stop_ord1    integer,
    next_stop_ord2    integer,
    next_stop_sec1    integer,
    next_stop_sec2    integer,
    next_stop_spd1    integer,
    next_stop_spd2    integer,
    plate_no1         varchar(255),
    plate_no2         varchar(255),
    predict_time1     integer,
    predict_time2     integer,
    ride_div1         integer,
    ride_div2         integer,
    ride_num1         integer,
    ride_num2         integer,
    route_id          varchar(255),
    route_type        integer,
    section_order1    integer,
    section_order2    integer,
    section_speed1    double precision,
    section_speed2    double precision,
    section_time1     integer,
    section_time2     integer,
    seq               integer,
    station_name1     varchar(255),
    station_name2     varchar(255),
    stop_id           varchar(255),
    term              integer,
    vehicle_id1       varchar(255),
    vehicle_id2       varchar(255)
);

alter table bus_arrival_raw
    owner to myuser;

create table bus_position_raw
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6),
    deleted_at    timestamp(6),
    updated_at    timestamp(6),
    bus_type      integer,
    collected_at  timestamp(6) not null,
    data_tm       varchar(255),
    is_running    varchar(255),
    last_stop_id  varchar(255),
    latitude      double precision,
    longitude     double precision,
    plain_no      varchar(255),
    route_id      varchar(255),
    section_order integer,
    section_speed double precision,
    stop_flag     varchar(255),
    stop_seq      integer,
    vehicle_id    varchar(255)
);

alter table bus_position_raw
    owner to myuser;

create table bus_route
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6),
    deleted_at     timestamp(6),
    updated_at     timestamp(6),
    company_name   varchar(255),
    end_station    varchar(255),
    first_bus_time varchar(255),
    first_low_time varchar(255),
    last_bus_time  varchar(255),
    last_bus_yn    varchar(255),
    last_low_time  varchar(255),
    route_id       varchar(255) not null
        constraint uk4mpxwmsh2stb1s1a7xmpe9tgi
            unique,
    route_name     varchar(255),
    route_type     integer,
    start_station  varchar(255),
    term           integer,
    total_distance double precision
);

alter table bus_route
    owner to myuser;

create table bus_stop
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    ars_id     varchar(255),
    latitude   double precision,
    longitude  double precision,
    stop_id    varchar(255) not null
        constraint uk60uakmdp0pyirsjksxcbewspm
            unique,
    stop_name  varchar(255),
    geom       geography(Point, 4326)
);

alter table bus_stop
    owner to myuser;

create table bus_route_stop
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6),
    deleted_at       timestamp(6),
    updated_at       timestamp(6),
    begin_tm         varchar(255),
    direction        varchar(255),
    last_tm          varchar(255),
    route_id         varchar(255)
        constraint fkomd2wsl60tar9dac5cww1o5vm
            references bus_route (route_id),
    section_distance double precision,
    section_id       varchar(255),
    section_speed    double precision,
    seq              integer,
    station_no       varchar(255),
    stop_id          varchar(255)
        constraint fkakjpni3kfpjeyy5jveppkuy2d
            references bus_stop (stop_id),
    transfer_yn      varchar(255),
    turn_stop_id     varchar(255)
);

alter table bus_route_stop
    owner to myuser;

create index idx_bus_stop_geom
    on bus_stop using gist (geom);

create table subway_arrival_raw
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6),
    deleted_at        timestamp(6),
    updated_at        timestamp(6),
    arrival_code      varchar(255),
    arrival_msg3      varchar(255),
    arrival_seconds   integer,
    collected_at      timestamp(6) not null,
    current_message   varchar(255),
    destination_id    varchar(255),
    destination_name  varchar(255),
    direction         varchar(255),
    last_train_yn     varchar(255),
    line_id           varchar(255),
    next_station_id   varchar(255),
    ordkey            varchar(255),
    prev_station_id   varchar(255),
    received_at       varchar(255),
    station_id        varchar(255),
    station_name      varchar(255),
    subway_id         varchar(255),
    train_line_name   varchar(255),
    train_no          varchar(255),
    train_type        varchar(255),
    transfer_count    integer,
    transfer_lines    varchar(255),
    transfer_stations varchar(255),
    constraint uk_subway_arrival_raw_observation
        unique (line_id, station_id, train_no, received_at, arrival_code, current_message)
);

alter table subway_arrival_raw
    owner to myuser;

create table subway_segment
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6),
    deleted_at        timestamp(6),
    updated_at        timestamp(6),
    arrive_station_id varchar(255),
    depart_station_id varchar(255),
    distance          double precision,
    line_id           varchar(255),
    seq               integer,
    travel_time       double precision
);

alter table subway_segment
    owner to myuser;

create table subway_station_tago
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6),
    deleted_at      timestamp(6),
    updated_at      timestamp(6),
    line_id         varchar(255),
    route_name      varchar(255),
    station_id      varchar(255),
    station_name    varchar(255),
    tago_station_id varchar(255) not null
        constraint ukcmrn5xiedqlfwt2o9avyk9gla
            unique
);

alter table subway_station_tago
    owner to myuser;

create table subway_timetable
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6),
    deleted_at       timestamp(6),
    updated_at       timestamp(6),
    arr_time         varchar(255),
    day_type         varchar(255),
    dep_time         varchar(255),
    direction        varchar(255),
    end_station_name varchar(255),
    line_id          varchar(255),
    station_name     varchar(255),
    subway_route_id  varchar(255),
    tago_station_id  varchar(255)
);

alter table subway_timetable
    owner to myuser;

create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    device_id  varchar(255) not null
        constraint uk6jl2ojdbeq8i75ouaqq7ks31
            unique
);

alter table users
    owner to myuser;

create table favorite_route
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    end_date   timestamp(6),
    end_place  varchar(255)     not null,
    ex         double precision not null,
    ey         double precision not null,
    type       varchar(255)     not null
        constraint favorite_route_type_check
            check ((type)::text = ANY
        ((ARRAY ['HOME'::character varying, 'WORK'::character varying])::text[])),
    user_id    bigint           not null
        constraint fk52nwfoo9kb1r616oiskhx548l
            references users
);

alter table favorite_route
    owner to myuser;

create table route_search_log
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6),
    deleted_at    timestamp(6),
    updated_at    timestamp(6),
    end_name      varchar(255),
    endx          double precision not null,
    endy          double precision not null,
    path_count    integer,
    response_json text,
    search_type   integer,
    searched_at   timestamp(6)     not null,
    start_name    varchar(255),
    startx        double precision not null,
    starty        double precision not null,
    user_id       bigint
        constraint fkicbchf6qpdqsrv1c4xam97sb5
            references users
);

alter table route_search_log
    owner to myuser;

create table subway_station
(
    id                  bigint default nextval('subway_station_source_id_seq'::regclass) not null
        constraint subway_station_source_pkey
            primary key,
    line_id             varchar(255),
    statn_id            varchar(255),
    statn_nm            varchar(255),
    search_line_name    varchar(255),
    kakao_query         varchar(255),
    latitude            double precision,
    longitude           double precision,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    deleted_at          timestamp(6),
    geom                geography(Point, 4326),
    tago_mapping_status varchar(255),
    tago_station_id     varchar(255)
);

alter table subway_station
    owner to myuser;

create index idx_subway_station_geom
    on subway_station using gist (geom);

create table subway_station_alias
(
    alias_name     varchar(255) not null
        primary key,
    canonical_name varchar(255) not null
);

alter table subway_station_alias
    owner to myuser;

create table subway_line_dictionary
(
    line_id                varchar(10)  not null
        primary key,
    canonical_line_name    varchar(100) not null,
    kakao_search_line_name varchar(100) not null,
    note                   varchar(255)
);

alter table subway_line_dictionary
    owner to myuser;

CREATE TABLE subway_arrival_event
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                 TIMESTAMP WITHOUT TIME ZONE,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE,
    deleted_at                 TIMESTAMP WITHOUT TIME ZONE,
    service_date               date                                    NOT NULL,
    line_id                    VARCHAR(255)                            NOT NULL,
    station_id                 VARCHAR(255)                            NOT NULL,
    station_name               VARCHAR(255),
    train_no                   VARCHAR(255)                            NOT NULL,
    direction                  VARCHAR(255)                            NOT NULL,
    destination_key            VARCHAR(255),
    destination_id             VARCHAR(255),
    destination_name           VARCHAR(255),
    train_type                 VARCHAR(255),
    event_source               VARCHAR(255),
    destination_conflicted     BOOLEAN,
    destination_conflict_count INTEGER,
    arrived_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    first_observed_at          TIMESTAMP WITHOUT TIME ZONE,
    last_observed_at           TIMESTAMP WITHOUT TIME ZONE,
    raw_count                  INTEGER,
    source_raw_ids             JSONB,
    CONSTRAINT pk_subway_arrival_event PRIMARY KEY (id)
);

ALTER TABLE subway_arrival_event
    ADD CONSTRAINT uk_subway_arrival_event UNIQUE (service_date, line_id, station_id, train_no,
                                                   direction, arrived_at);

