-- IT 전용 최소 스키마. bus_arrival_alert 의 partial unique index 동작 검증용.
-- (전체 Flyway 체인은 V1 baseline 이 postgis 내장 객체와 충돌하므로 IT 에선 미사용.
--  실제 V19 는 prod 배포 시 Flyway baseline 위에서 적용된다.)

CREATE TABLE users (
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    deleted_at    timestamp(6),
    toss_user_key bigint
);

-- V19__create_bus_arrival_alert.sql 과 동일한 정의 (drift 시 IT 가 깨져 알려줌).
CREATE TABLE bus_arrival_alert (
    id                    bigint generated by default as identity primary key,
    created_at            timestamp(6),
    updated_at            timestamp(6),
    deleted_at            timestamp(6),
    user_id               bigint        not null references users,
    stop_id               varchar(255)  not null,
    route_id              varchar(255)  not null,
    ord                   integer       not null,
    route_name            varchar(255)  not null,
    stop_name             varchar(255)  not null,
    user_eta              timestamp(6)  not null,
    status                varchar(255)  not null
        constraint bus_arrival_alert_status_check
            check (status in ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'EXPIRED', 'CANCELED')),
    expires_at            timestamp(6)  not null,
    sent_at               timestamp(6),
    processing_started_at timestamp(6),
    last_attempt_at       timestamp(6),
    attempt_count         integer       not null default 0,
    last_failure_reason   varchar(500)
);

CREATE UNIQUE INDEX uq_bus_alert_active
    ON bus_arrival_alert (user_id, stop_id, route_id, ord)
    WHERE deleted_at IS NULL AND status IN ('PENDING', 'PROCESSING');
CREATE INDEX idx_bus_alert_status_expires
    ON bus_arrival_alert (status, expires_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_bus_alert_stop_route_ord
    ON bus_arrival_alert (stop_id, route_id, ord) WHERE deleted_at IS NULL;
